# Generated by Django 4.2.2 on 2023-06-25 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('incomes', '0003_remove_income_category_income_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='categories',
            field=models.ManyToManyField(to='categories.incomecategory'),
        ),
    ]
