# Generated by Django 4.2.2 on 2023-06-25 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_alter_expense_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='expense_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
