# Generated by Django 4.2.2 on 2023-06-25 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('expenses', '0004_remove_expense_category_expense_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='categories',
            field=models.ManyToManyField(to='categories.expensecategory'),
        ),
    ]
